# Generated by Django 5.0.12 on 2025-03-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
